export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_USERS = 'FETCH_USERS';

export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const PRODUCTS_FAILED = 'PRODUCTS_FAILED';
export const ADD_CART_ITEMS = 'ADD_CART_ITEMS';

export const ADJUST_QTY = 'ADJUST_QTY';
export const LOAD_CURRENT_ITEM = 'LOAD_CURRENT_ITEM';

export const PRODUCT_DETAILS_REQUEST ='PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS ='PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL ='PRODUCT_DETAILS_FAIL';
export const CART_SAVE_SHIPPING = 'CART_SAVE_SHIPPING';
export const CART_SAVE_PAYMENT = 'CART_SAVE_PAYMENT';

export const CART_ITEMS_LOADING = 'CART_ITEMS_LOADING';
export const CART_ITEMS_FAILED = 'CART_ITEMS_FAILED';
export const REMOVE_FROM_CART ='REMOVE_FROM_CART'
export const FETCH_ORDERS = 'FETCH_ORDERS';
export const CREATE_ORDER = 'CREATE_ORDER';
export const CLEAR_ORDER = 'CLEAR_ORDER';
export const CLEAR_CART ='CLEAR_CART'
export const AUTH="AUTH";
export const ALERT = 'ALERT';


export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL';
// export const ADD_COMMENTS = 'ADD_COMMENTS';
// export const COMMENTS_FAILED = 'COMMENTS_FAILED';
// export const ADD_COMMENT = 'ADD_COMMENT';

export const USER_SIGN_OUT_SUCCESS = 'USER_SIGN_OUT_SUCCESS';
export const USER_SIGN_OUT_FAIL = ' USER_SIGN_OUT_FAIL';
